function [trained_params] = TrainMediumModel(initial_params_unrolled,...
                                  Input_Layer_Size,...
                                  Hidden_Layer_1_Size,...
                                  Hidden_Layer_2_Size, ...
                                  Output_Layer_Size,...
                                  trainXR, trainY,...
                                  lambda, options)
costFunction = @(p) MediumnnCostFunction(p, ...
                                        Input_Layer_Size, ...
                                        Hidden_Layer_1_Size, ...
                                        Hidden_Layer_2_Size, ...
                                        Output_Layer_Size, trainXR, trainY, lambda);

[trained_params, cost_trail] = fmincg(costFunction, initial_params_unrolled, options);

end