function [trained_params] = TrainLargeModel(initial_params_unrolled,...
                                           Input_Layer_Size,...
                                           Hidden_Layer_1_Size,...
                                           Hidden_Layer_2_Size, ...
                                           Hidden_Layer_3_Size, ...
                                           Output_Layer_Size,...
                                           trainXR, trainY,...
                                           lambda, options)

%Binding Cost Function
CostFunction = @(p) LargennCostFunction(p, ...
                                        Input_Layer_Size, ...
                                        Hidden_Layer_1_Size, ...
                                        Hidden_Layer_2_Size, ...
                                        Hidden_Layer_3_Size, ...
                                        Output_Layer_Size,...
                                        trainXR, trainY, lambda);
%Optimizing Weights/Theta
[trained_params, cost_trail] = fmincg(CostFunction, initial_params_unrolled, options);

end